version: '3.9'

services:
  garmin-sync:
    build: .
    container_name: garmin_app
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - data:/opt/garmin/out
    environment:
      - TZ=America/CHIHUAHUA

volumes:
  data:
