version: '3.9'

services:
  garmin-sync:
    build: .
    container_name: garmin_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Mapea la carpeta 'out' de tu servidor a la carpeta 'out' que espera la app dentro del contenedor
      - ./out:/app/out
    environment:
      - TZ=America/CHIHUAHUA
